## Bakery Recipes

#### Author: Yesahel Scicluna 

#### Source: Codecademy. Learn Statistics with NumPy. Practice Project - Betty's Bakery

#### Concepts: NumPy, element-wise operation, nd-arrays

#### Required Data Files: recipes.csv

#### Task Description
Betty has always used her grandmother’s recipe book to make cookies, cakes, pancakes, and bread for her friends and family. She’s getting ready to open a business and will need to start buying all of her milk, eggs, sugar, flour, and butter in bulk. Help Betty figure out how much she needs to buy using NumPy arrays describing her recipes.

#### Task 1
Start by importing NumPy as `np`.

In [1]:
import numpy as np

#### Task 2
All of Betty’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:
 - Flour: 2 cups
 - Sugar: 0.75 cups
 - Eggs: 2 eggs
 - Milk: 1 cups
 - Butter: 0.5 cups

Create a NumPy array that represents this data. Each element should be a number. Save this array as `cupcakes`.

In [2]:
cupcakes = np.array([2, 0.75, 2, 1, 0.5])
cupcakes

array([2.  , 0.75, 2.  , 1.  , 0.5 ])

#### Task 3
Betty’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called `recipes`.

In [3]:
# Update the code below with the correct filepath of recipes.csv
recipes = np.genfromtxt(r'C:\path\to\file\recipes.csv', delimiter = ',') 

#### Task 4
Display `recipes`. Each row represents a different recipe. Each column represents a different ingredient.

In [4]:
recipes

array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

#### Task 5
The 3rd column represents the number of eggs that each recipe needs. Select all elements from the 3rd column and save them to the variable `eggs`.

In [5]:
eggs = recipes[:,2]
eggs

array([2., 1., 1., 2.])

#### Task 6
Which recipes require exactly 1 egg? Use a logical statement to get `True` or `False` for each value of `eggs`.

In [6]:
one_egg = eggs == 1
one_egg

array([False,  True,  True, False])

#### Task 7
Betty is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).
You already have a variable for `cupcakes`. Create a variable for `cookies` with the data from the 3rd row.

In [7]:
cookies = recipes[2, :]
cookies

array([2.75, 1.5 , 1.  , 0.  , 1.  ])

#### Task 8
Get the number of ingredients for a double batch of `cupcakes` by using multiplication on cupcakes. Save your new variable to `double_batch`.

In [8]:
double_batch = cupcakes * 2
double_batch

array([4. , 1.5, 4. , 2. , 1. ])

#### Task 9
Create a new variable called `grocery_list` by adding `cookies` and `double_batch`.

In [9]:
grocery_list = cookies + double_batch
grocery_list

array([6.75, 3.  , 5.  , 2.  , 2.  ])